package com.rdsr.gameoflife.cell;

/**
 * Simple immutable class representing a cell in a 2D World
 */
public class TwoDPosition implements Position, Comparable<TwoDPosition> {
  final int i, j;

  public TwoDPosition(int i, int j) {
    this.i = i;
    this.j = j;
  }

  public int getI() {
    return i;
  }

  public int getJ() {
    return j;
  }

  public int compareTo(TwoDPosition other) {
    return i - other.i == 0 ? j - other.j : i - other.i;
  }

  @Override
  public String toString() {
    return "Position(" + i + " " + j + ")";
  }

  /**
   * auto generated by eclipse
   */
  @Override
  public int hashCode() {
    final int prime = 31;

    int result = 1;
    result = prime * result + i;
    result = prime * result + j;

    return result;
  }

  /**
   * auto generated by eclipse
   */
  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;

    if (obj == null)
      return false;

    if (getClass() != obj.getClass())
      return false;

    final TwoDPosition other = (TwoDPosition) obj;
    if (i != other.i)
      return false;

    if (j != other.j)
      return false;

    return true;
  }
}
